/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 18 15:45:01 GMT 2016
 */

package org.objectweb.cjdbc.common.exceptions;

import org.junit.Test;
import static xcorpus.AssertionAdapter.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.objectweb.cjdbc.common.exceptions.RollbackException;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class RollbackException_ESTest extends RollbackException_ESTest_scaffolding {

  //Test case number: 0
  /*
   * 1 covered goal:
   * Goal 1. org.objectweb.cjdbc.common.exceptions.RollbackException.<init>()V: root-Branch
   */

	@Test(timeout=300000)
  public void test0()  throws Throwable  {
      RollbackException rollbackException0 = new RollbackException();
  }

  //Test case number: 1
  /*
   * 2 covered goals:
   * Goal 1. org.objectweb.cjdbc.common.exceptions.RollbackException.<init>(Ljava/lang/Throwable;)V: root-Branch
   * Goal 2. org.objectweb.cjdbc.common.exceptions.RollbackException.<init>(Ljava/lang/String;)V: root-Branch
   */

	@Test(timeout=300000)
  public void test1()  throws Throwable  {
      RollbackException rollbackException0 = new RollbackException("");
      RollbackException rollbackException1 = new RollbackException((Throwable) rollbackException0);
      assertFalse(rollbackException1.equals((Object)rollbackException0));
  }

  //Test case number: 2
  /*
   * 2 covered goals:
   * Goal 1. org.objectweb.cjdbc.common.exceptions.RollbackException.<init>(Ljava/lang/String;)V: root-Branch
   * Goal 2. org.objectweb.cjdbc.common.exceptions.RollbackException.<init>(Ljava/lang/String;Ljava/lang/Throwable;)V: root-Branch
   */

	@Test(timeout=300000)
  public void test2()  throws Throwable  {
      RollbackException rollbackException0 = new RollbackException("");
      RollbackException rollbackException1 = new RollbackException("", (Throwable) rollbackException0);
      assertFalse(rollbackException1.equals((Object)rollbackException0));
  }
}
